language: java
before_install:
  ##########
  # TEMPORARY hack to get around Travis not installing Java
  # Remove this and the ".travis_install_jdk.sh" file once Travis installs java properly again!
  # Copied from the output of the "install_jdk" task in our last successful build
  - export JAVA_HOME=~/openjdk18
  - export PATH="$JAVA_HOME/bin:$PATH"
  - ./install-jdk.sh --target "/home/travis/openjdk18" --workspace "/home/travis/.cache/install-jdk" --feature "18" --license "GPL" --cacerts
  ##########
jdk: openjdk8
install: true
cache:
  directories:
  - $HOME/.m2
script: mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V 
