apiVersion: v2
name: regproc-workflow
description: A Helm chart for MOSIP Registration Processor Workflow Manager
type: application
version: 12.1.1
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - regproc-workflow
  - regproc
maintainers:
  - email: info@mosip.io
    name: MOSIP
